server:
  port: 8008

spring:
  datasource:
    druid:
      url: jdbc:mysql://www.lovecoding.online:3306/online_exam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall

logging:
  level:
    com.yb.onlineexamserver.mbg.mapper: debug
    com.yb.onlineexamserver.dao: debug

mybatis:
  mapper-locations:
    - classpath:com/yb/onlineexamserver/mbg/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true